//! Cross-validation of the multivariate kernel regression / density estimators
//! against golden reference values frozen in
//! `tests/fixtures/nonparametric_ext.json` (generated by
//! `tools/reference/gen_nonparametric_ext.py`).

use ndarray::{Array1, Array2};
use serde_json::Value;
use solow_nonparametric::{KdeMultivariate, KernelReg, RegType};
use std::fs;

fn load() -> Value {
    let p = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/fixtures/nonparametric_ext.json"
    );
    let s = fs::read_to_string(p)
        .expect("fixture present (run tools/reference/gen_nonparametric_ext.py)");
    serde_json::from_str(&s).unwrap()
}

fn vec1(v: &Value) -> Array1<f64> {
    Array1::from_vec(
        v.as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_f64().unwrap())
            .collect(),
    )
}

/// Parse a JSON `n × d` array-of-arrays into an `Array2<f64>`.
fn mat(v: &Value) -> Array2<f64> {
    let rows: Vec<Vec<f64>> = v
        .as_array()
        .unwrap()
        .iter()
        .map(|r| {
            r.as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_f64().unwrap())
                .collect()
        })
        .collect();
    let (m, n) = (rows.len(), rows[0].len());
    Array2::from_shape_vec((m, n), rows.into_iter().flatten().collect()).unwrap()
}

fn bw_of(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn rel(got: f64, want: f64) -> f64 {
    (got - want).abs() / (1.0 + want.abs())
}

fn check_vec(label: &str, got: &Array1<f64>, want: &Array1<f64>, tol: f64) {
    assert_eq!(got.len(), want.len(), "{label}: length mismatch");
    for i in 0..got.len() {
        let e = rel(got[i], want[i]);
        assert!(
            e <= tol,
            "{label}[{i}]: rel-err {e:.3e} (got {}, want {})",
            got[i],
            want[i]
        );
    }
}

fn reg_type_for(name: &str) -> RegType {
    match name {
        "ll" => RegType::LocalLinear,
        "lc" => RegType::LocalConstant,
        other => panic!("unknown reg_type {other}"),
    }
}

#[test]
fn kernel_reg_matches_reference() {
    let fx = load();
    for c in fx["kernel_reg"].as_array().unwrap() {
        let name = c["name"].as_str().unwrap();
        let reg_type = reg_type_for(c["reg_type"].as_str().unwrap());
        let endog = vec1(&c["endog"]);
        let exog = mat(&c["exog"]);
        let bw = bw_of(&c["bw"]);
        let grid = mat(&c["grid"]);

        let model = KernelReg::new(endog, exog, bw, reg_type).unwrap();
        let mean = model.fit(&grid).unwrap();

        // Fitted mean on the grid: closed-form NW / weighted-LS to ≤1e-7.
        check_vec(
            &format!("kernel_reg.{name}.mean"),
            &mean,
            &vec1(&c["mean"]),
            1e-7,
        );
    }
}

#[test]
fn kde_multivariate_matches_reference() {
    let fx = load();
    for c in fx["kde_multivariate"].as_array().unwrap() {
        let name = c["name"].as_str().unwrap();
        let data = mat(&c["data"]);
        let bw = bw_of(&c["bw"]);
        let grid = mat(&c["grid"]);

        let kde = KdeMultivariate::new(data, bw).unwrap();
        let dens = kde.pdf(&grid).unwrap();

        // Product-Gaussian density on the grid: closed-form to ≤1e-7.
        check_vec(
            &format!("kde_multivariate.{name}.density"),
            &dens,
            &vec1(&c["density"]),
            1e-7,
        );
    }
}
